### ISSUE TITLE
Chrome 116無法顯示3D立繪

### ISSUE THREAD

**Issue by ivon852** [laplamgor/kantai3d-chrome-extension#1]
Google Chrome 116 / Microsoft Edge 115皆無法顯示3D立繪，使用的是內建支援的艦娘。

Console顯示資源有成功載入，已嘗試清除資料、停用KC3改用VPN，仍然看不到立繪。

![](https://i.imgur.com/FJAau9V.jpg)

**Comment by laplamgor** [comment]
~~請問是什麼GPU硬件, 系統~~
~~因為shader消失大概率和GPU渲染有關係~~
~~顯卡驅動不正常/顯存不夠都有可能出錯~~

~~另外打開遊戲前打開F12看一下Console有沒有這句~~
~~確保遊戲是用WEBGL模式運行(而不是CANVAS)~~
~~![image](https://github.com/laplamgor/kantai3d-chrome-extension/assets/11514317/442e078e-d023-4b88-861a-bcac6d369435)~~


重現了

**Comment by laplamgor** [comment]
Fixed in 3.7
gotobrowser / poi plugin will be updated very soon
